#!/usr/bin/env bash
# This script displays username, user id and home directory from /etc/passwd

# shellcheck disable=SC2034
while IFS=: read -r username password uid gid comment home shell
do
    echo "$username:$uid:$home"
done < /etc/passwd
